### ISSUE TITLE
jsonrpc for Odoo/OpenERP 7?

### ISSUE THREAD

**Issue by ericmachine88** [0k/php-oe-json#3]
Like to confirm again that Odoo/OpenERP 7 community edition can support jsonrpc?
Do I need to enable any settings i.e. openerp-server.conf?
I have tested other examples i.e.
http://localhost:8069/jsonrpc -> that returns me a 404 error
I have tried similar pythons library but couldn't get this working.
any help? Thanks.

**Comment by vaab** [comment]
Hi, I'm not very sure of what you are talking about.
Just to rephrase some evidence : you are commenting on a github repository that is an example of how to communicate with openerp v7 using PHP and jsonrpc. This repository is not related with openerp/odoo company.
As the examples of this repository objective is to show how to use jsonrpc, the answer to your first question as I understand it is "Yes, I can confirm you that json OpenERP v7 can support jsonrpc."
To the second question: "No, you don't need to enable any settings in openerp-server.conf".

Your statement about trying "http://localhost:8069/jsonrpc" does not make sense for me: where does "/jsonrpc" comes from ? and why do you expect it to give you something else than 404 ?

There are numerous entry-points to both http requests ans jsonrpc request, identified by different urls. You could try "/web/database/get_list" is a valid jsonrpc url for instance. Note that it requires several values to be correctly set in POST to be accepted and processed accordingly. This is why you need a library if you want to avoid building yourselves the correct HTTP requests.

But OpenERP itself is already json-rpc ready. What you need is client side. There a numerous python library that plug in openerp or that could help you build json-rpc clients.

Hope this helps.

**Comment by ericmachine88** [comment]
Thanks for the kind explanations. Yes, you are right on this :)
